module.exports = {
    CREATE_CHAT:"CREATE_CHAT",
    COMMUNITY_CHAT:"COMMUNITY_CHAT",
    USER_CONNECTED:"USER_CONNECTED",
    MESSAGE_RECIEVED:"MESSAGE_RECIEVED",
    MESSAGE_SENT:"MESSAGE_SENT",
    USER_DISCONNECTED:"USER_DISCONNECTED",
    TYPING:"TYPING",
    SEND_TYPING:"SEND_TYPING",
    VERIFY_USER:"VERIFY_USER",
    PRIVATE_MESSAGE:"PRIVATE_MESSAGE",
    LOGOUT:"LOGOUT",
    IS_USER_CONNECTED:"IS_USER_CONNECTED",
    CLOSE_CHAT_ROOM:"CLOSE_CHAT_ROOM"
}